# Generated by Django 6.0.2 on 2026-03-02 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('agent_type', models.CharField(choices=[('trading', 'Trading'), ('prediction', 'Prediction'), ('orchestrator', 'Orchestrator'), ('monitor', 'Monitor'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('retired', 'Retired'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('soul_file', models.TextField(blank=True, help_text='Markdown personality/config content')),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, help_text='Visible prefix (ak_xxxxxxxx)', max_length=12)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full key', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent API Key',
                'verbose_name_plural': 'Agent API Keys',
            },
        ),
        migrations.CreateModel(
            name='AgentLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('exclusive', 'Exclusive'), ('non_exclusive', 'Non-Exclusive'), ('open_source', 'Open Source'), ('evaluation', 'Evaluation')], max_length=20)),
                ('licensee_name', models.CharField(max_length=200)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_share_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=200)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('creator_url', models.URLField(blank=True, help_text='GitHub/LinkedIn profile')),
                ('revenue_share_pct', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('chain_verified', models.BooleanField(default=False)),
                ('chain_address', models.CharField(blank=True, max_length=42)),
                ('chain_tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Ownership',
                'verbose_name_plural': 'Agent Ownerships',
            },
        ),
        migrations.CreateModel(
            name='AgentReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=50)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('profitability_score', models.FloatField(default=0.0)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('total_decisions', models.IntegerField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('profit_factor', models.FloatField(default=0.0)),
                ('sharpe_ratio', models.FloatField(default=0.0)),
                ('max_drawdown_pct', models.FloatField(default=0.0)),
                ('brier_score', models.FloatField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_window_days', models.IntegerField(default=30)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Reputation',
            },
        ),
    ]
