# Generated by Django 6.0.2 on 2026-03-02 05:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_id', models.CharField(db_index=True, max_length=100)),
                ('instrument', models.CharField(blank=True, max_length=30)),
                ('final_outcome', models.CharField(choices=[('pass', 'Pass'), ('block', 'Block'), ('modify', 'Modify'), ('win', 'Win'), ('loss', 'Loss'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=10)),
                ('total_stages', models.IntegerField(default=0)),
                ('passed_stages', models.IntegerField(default=0)),
                ('blocked_at_stage', models.CharField(blank=True, max_length=30)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='agents.agent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('price_fetch', 'Price Fetch'), ('momentum', 'Momentum Analysis'), ('market_lean', 'Market Lean Detection'), ('edge_gate', 'Edge Gate'), ('circuit_breaker', 'Circuit Breaker'), ('signal', 'Signal Generation'), ('trend_filter', 'Trend Filter'), ('regime', 'Regime Detection'), ('ranking', 'Signal Ranking'), ('risk_validation', 'Risk Validation'), ('execution', 'Execution'), ('resolution', 'Resolution'), ('claim', 'Claim'), ('heartbeat', 'Heartbeat'), ('prediction', 'Prediction'), ('trade', 'Trade'), ('error', 'Error')], db_index=True, max_length=30)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('block', 'Block'), ('modify', 'Modify'), ('win', 'Win'), ('loss', 'Loss'), ('pending', 'Pending'), ('error', 'Error')], db_index=True, default='pending', max_length=10)),
                ('instrument', models.CharField(blank=True, db_index=True, max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('cycle_id', models.CharField(blank=True, db_index=True, help_text='Groups events from the same decision cycle', max_length=100)),
                ('duration_ms', models.IntegerField(blank=True, help_text='How long this step took (ms)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agent')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.decisionpipelinerun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('instrument', models.CharField(blank=True, max_length=30)),
                ('tier', models.CharField(blank=True, max_length=30)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.agent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'name', '-timestamp'], name='events_agen_agent_i_4f0c95_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='decisionpipelinerun',
            index=models.Index(fields=['agent', '-started_at'], name='events_deci_agent_i_d5aefd_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['agent', '-timestamp'], name='events_agen_agent_i_f38190_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['agent', 'event_type', '-timestamp'], name='events_agen_agent_i_25086f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['cycle_id', 'timestamp'], name='events_agen_cycle_i_e7973b_idx'),
        ),
    ]
